#!/bin/bash
set -e -E -u

IP=$(ip addr show eth0 | sed "/ inet /{s#/.*##;s#.* ##;p};d")
FQDN=$HOSTNAME.node.consul

sed -i "/^nodename/{s/127.0.0.1/$FQDN/g};/^[^#]/{s/127.0.0.1/0.0.0.0/g}" /etc/riak/riak.conf

service riak restart
riak-admin bucket-type create yadt '{"props":{"allow_mult":false,"last_write_wins":true}}'
riak-admin bucket-type activate yadt
