#!/bin/bash

DOCROOT="http://node1.node.consul:8098/riak/yadt"

for HTML in *.html; do
    curl -XPUT $DOCROOT/$HTML -H 'Content-Type:text/html' -d "$(cat $HTML)"
done
for JS in *.js; do
    curl -XPOST $DOCROOT/$JS -H 'Content-Type:text/javascript' -d @$JS
done
for CSS in *.css; do
    curl -XPOST $DOCROOT/$CSS -H 'Content-Type:text/css' -d @$CSS
done
