#!/bin/bash
#
# chkconfig: 2345 56 26
# Description: init script for the dist-wamp-router
#

set -e -E -u


CONFIGFILE=/etc/sysconfig/dist-wamp-router
USER=dist-wamp-router
[[ -r $CONFIGFILE ]] && source $CONFIGFILE
PROGRAM=/opt/dist-wamp-router/dist_wamp_router/bin/dist_wamp_router
SHORT_PROGRAM=$(basename $PROGRAM)

case "${1:-}" in
    start)
        if $0 status; then
            echo "$SHORT_PROGRAM already running";
        else
            echo "Starting $SHORT_PROGRAM";
            runuser -l $USER -c "$PROGRAM start";
       fi
    ;;
    stop)
        if $0 status; then
            runuser -l $USER -c "$PROGRAM stop";
        else
            echo "$SHORT_PROGRAM already stopped";
        fi
    ;;
    status)
        if runuser -l $USER -c "$PROGRAM ping"; then
            exit 0;
        else
            exit 3;
        fi
    ;;
    restart)
        runuser -l $USER -c "$PROGRAM restart"
    ;;
    *)
        echo "Usage: $0 {start|stop|status|restart}" >&2 && exit 3
    ;;
esac
