#!/bin/bash
#
# chkconfig: 2345 56 26
# Description: init script for the dist-wamp-router
#

set -e -E -u


CONFIGFILE=/etc/sysconfig/dist-wamp-router
UID=dist-wamp-router
[[ -r $CONFIGFILE ]] && source $CONFIGFILE
PROGRAM=/opt/dist-wamp-router/dist_wamp_router/bin/dist_wamp_router
LAUNCHER="runuser -l $uid -c $PROGRAM"

case "${1:-}" in
    start)
        if $0 status; then
            echo "$0 already running";
        else
            echo "Starting $0";
            $LAUNCHER start;
       fi
    ;;
    stop)
        if $0 status; then
            $LAUNCHER stop;
        else
            echo "$0 already stopped";
        fi
    ;;
    status)
        echo 'Pinging the dist-wamp-router, expect "pong"'
        $LAUNCHER ping
    ;;
    restart)
        $LAUNCHER restart
    ;;
    *)
        echo "Usage: $0 {start|stop|status|restart}" >&2 && exit 3
    ;;
esac
